# Generated by Django 3.1.7 on 2021-04-25 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=17)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marchant_invoice_id', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('product_type', models.CharField(choices=[('Fragile', 'Fragile'), ('Liquid', 'Liquid')], max_length=50)),
                ('location_type', models.CharField(choices=[('Inside_Dhaka', 'Inside_Dhaka'), ('Division_of_Dhaka', 'Division_of_Dhaka'), ('Outside_Dhaka', 'Outside_Dhaka')], max_length=50)),
                ('weight', models.FloatField()),
                ('marchant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchant_name', to='orders.merchant')),
            ],
        ),
    ]
