# Generated by Django 3.1.7 on 2021-04-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='price_with_cod',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='price_with_return_charges',
            field=models.FloatField(default=0),
        ),
    ]
