# Generated by Django 3.1.7 on 2021-04-26 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210426_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='price_with_all_facility',
        ),
    ]
