# Generated by Django 3.1.7 on 2021-04-26 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_subdistrict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='district',
        ),
        migrations.AddField(
            model_name='orders',
            name='subdistrict',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subdis_name', to='orders.subdistrict'),
        ),
    ]
